### ISSUE TITLE
custom baord build fails when enabling connector yaml.

### ISSUE THREAD

**Issue by jcor25** [rusefi/fw-custom-example#9]
after changing the original name of custom_firmware.yaml_template to custom_firmware.yaml to enable building code, build fails, error code it gets hung up on is.

`E 240611 021119.691 [main] WriteSimulatorConfiguration - Unfortunately
java.lang.IllegalStateException: Ordinal out of range 130 in vvtPins1
	at com.opensr5.ini.field.EnumIniField.getValue(EnumIniField.java:58)
	at com.rusefi.tune.xml.Msq.loadConstant(Msq.java:85)
	at com.rusefi.tune.xml.Msq.valueOf(Msq.java:39)
	at com.rusefi.binaryprotocol.MsqFactory.valueOf(MsqFactory.java:10)
	at com.rusefi.tools.tune.WriteSimulatorConfiguration.readBinaryWriteXmlTune(WriteSimulatorConfiguration.java:92)
	at com.rusefi.tools.tune.WriteSimulatorConfiguration.main(WriteSimulatorConfiguration.java:37)
Error: Process completed with exit code 255.`

**Comment by rusefillc** [comment]
@jcor25 fixed!
